
variables:
  APPLICATION_NAME: file-poster
  DOCKER_IMAGE: ${DOCKER_HUB_USERNAME}/${APPLICATION_NAME}
  DOCKER_IMAGE_TAGGED: ${DOCKER_IMAGE}:${CI_COMMIT_SHORT_SHA}
  K8S_NODEPORT: 30020
  K8S_INGRESS_HOST: fileposter.home.maximemoreillon.com

build:
  stage: build
  tags:
    - moreillon
  script:
    # Docker hub login
    - echo "${DOCKER_HUB_PASSWORD}" | docker login --username ${DOCKER_HUB_USERNAME} --password-stdin
    # Building the container image
    - docker build -t ${DOCKER_IMAGE} .
    # Tagging
    - docker tag ${DOCKER_IMAGE} ${DOCKER_IMAGE_TAGGED}
    # Pushing the image to the registry
    - docker push ${DOCKER_IMAGE}
    - docker push ${DOCKER_IMAGE_TAGGED}
    # Cleanup
    - docker image rm ${DOCKER_IMAGE}
    - docker image rm ${DOCKER_IMAGE_TAGGED}

deploy:
  stage: deploy
  tags:
    - moreillon
  script:
    - envsubst < kubernetes_manifest.yml | kubectl apply -f -
  environment:
    name: production
    kubernetes:
      namespace: ${KUBERNETES_NAMESPACE}
