variables:
  APPLICATION_NAME: file-poster
  DOCKER_IMAGE: ${DOCKER_HUB_USERNAME}/${APPLICATION_NAME}
  DOCKER_IMAGE_TAGGED: ${DOCKER_IMAGE}:${CI_COMMIT_TAG}

image: moreillon/ci-dind
services:
  - name: docker:24.0.7-dind

build:
  stage: build
  only:
    - tags
  before_script:
    - echo "${DOCKER_HUB_PASSWORD}" | docker login --username ${DOCKER_HUB_USERNAME} --password-stdin
  script:
    - docker build -t ${DOCKER_IMAGE} .
    - docker tag ${DOCKER_IMAGE} ${DOCKER_IMAGE_TAGGED}
    - docker push ${DOCKER_IMAGE}
    - docker push ${DOCKER_IMAGE_TAGGED}
