apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APPLICATION_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${APPLICATION_NAME}
  template:
    metadata:
      labels:
        app: ${APPLICATION_NAME}
    spec:
      containers:
      - name: ${APPLICATION_NAME}
        image: ${DOCKER_IMAGE}
        # Ensures that k8s pulls a new image on restart
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ${APPLICATION_NAME}
spec:
  type: NodePort
  selector:
    app: ${APPLICATION_NAME}
  ports:
  - port: 80
    nodePort: ${K8S_NODEPORT}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ${APPLICATION_NAME}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod" # This is necessary, no idea why
    nginx.ingress.kubernetes.io/proxy-body-size: "5g"
    nginx/client_max_body_size: 5g
spec:
  tls:
  - hosts:
    - ${K8S_INGRESS_HOST}
    secretName: ${APPLICATION_NAME}
  rules:
  - host: ${K8S_INGRESS_HOST}
    http:
      paths:
      - path: /
        backend:
          serviceName: ${APPLICATION_NAME}
          servicePort: 80
